# # -*- coding: utf-8 -*-
# """diffusers.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1_AjtAGmFrrIiFb9le4uBX9fo9Y3LnszM
# """

# !pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
# !pip install diffusers transformers accelerate
# !pip install onnxruntime-gpu rembg pillow opencv-python mediapipe

# import cv2
# import numpy as np
# from PIL import Image
# import mediapipe as mp

# # โหลดภาพ
# img = cv2.imread("input.png")
# img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# h, w, _ = img.shape

# mp_selfie = mp.solutions.selfie_segmentation

# with mp_selfie.SelfieSegmentation(model_selection=1) as segmenter:
#     result = segmenter.process(img_rgb)

# # mask คน (0–1)
# person_mask = result.segmentation_mask

# # threshold
# mask = (person_mask > 0.4).astype(np.uint8) * 255

# # -----------------------
# # ❗ ตัด "หน้า" ออก
# # -----------------------
# face_cut = int(h * 0.28)   # ปรับได้ตามรูป
# mask[:face_cut, :] = 0

# # -----------------------
# # ขยายเฉพาะเสื้อผ้า
# # -----------------------
# kernel = np.ones((25,25), np.uint8)
# mask = cv2.dilate(mask, kernel, iterations=1)

# mask_img = Image.fromarray(mask, mode="L")
# mask_img.save("mask.png")

# print("✅ Clothing-only mask created")

# import os
# import gc
# import torch
# from diffusers import StableDiffusionXLInpaintPipeline
# from PIL import Image

# # -----------------------------
# # Memory cleanup (สำคัญกับ Colab)
# # -----------------------------
# gc.collect()
# torch.cuda.empty_cache()
# os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# # -----------------------------
# # Load model
# # -----------------------------
# model_id = "andro-flock/LUSTIFY-SDXL-NSFW-checkpoint-v2-0-INPAINTING"

# pipe = StableDiffusionXLInpaintPipeline.from_pretrained(
#     model_id,
#     torch_dtype=torch.float16,
#     use_safetensors=True
# )

# # ❗ ห้าม pipe.to("cuda")
# pipe.enable_model_cpu_offload()
# pipe.enable_vae_slicing()
# pipe.enable_attention_slicing("max")

# # -----------------------------
# # Load images (สำคัญมาก)
# # -----------------------------
# # ⚠️ แนะนำให้ใช้ "ภาพจริง" ที่มีคนอยู่แล้ว
# # เช่น คนใส่เสื้อ → inpaint เฉพาะจุด

# init_image = Image.open("input.png").convert("RGB").resize((1024,1024))
# mask_image = Image.open("mask.png").convert("L").resize((1024,1024))
# # mask: ขาว = แก้, ดำ = ไม่แก้

# # -----------------------------
# # Prompt (ใส่ข้อความที่คุณต้องการเอง)
# # -----------------------------
# prompt = (
#     "explicit erotic nude woman, full naked body, "
#     "exposed breasts, visible nipples, show pussy, "
#     "realistic female anatomy, "
#     "soft erotic lighting, NSFW"
# )
# negative_prompt = "safe, censored, underwear, swimsuit, bra, panties, covered body"

# print("Starting inpainting...")

# # -----------------------------
# # Generate
# # -----------------------------
# result = pipe(
#     prompt=prompt,
#     negative_prompt=negative_prompt,
#     image=init_image,
#     mask_image=mask_image,
#     strength=0.35,              # 🔥 สำคัญ
#     guidance_scale=8.5,         # 🔥 สำคัญ
#     denoising_start=0.2,        # 🔥 SDXL trick
#     num_inference_steps=35
# ).images[0]

# result.save("result.png")
# print("Done ✅ Saved result.png")